version: "3.9"

volumes:
  logs:

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "15672:15672"
    volumes:
      - ./rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 5s
      retries: 10

  telemetry:
    build:
      context: .
      dockerfile: telemetry/Dockerfile
    environment:
      LOG_FILE: /logs/app.log
    volumes:
      - logs:/logs

  service_a:
    build:
      context: .
      dockerfile: service_a/Dockerfile
    ports:
      - "50051:50051"
    environment:
      TELEMETRY_HOST: "telemetry:50051"
      RABBITMQ_URL: "amqp://guest:guest@rabbitmq:5672/"
      FILE_TASK_PARTITIONS: "4"
    depends_on:
      rabbitmq:
        condition: service_healthy
      telemetry:
        condition: service_started
    restart: on-failure

  service_b_0:
    build:
      context: .
      dockerfile: service_b/Dockerfile
    environment:
      TELEMETRY_HOST: "telemetry:50051"
      RABBITMQ_URL: "amqp://guest:guest@rabbitmq:5672/"
      FILE_WORKER_PARTITION_INDEX: "0"
    depends_on:
      rabbitmq:
        condition: service_healthy
      telemetry:
        condition: service_started
    restart: on-failure

  service_b_1:
    build:
      context: .
      dockerfile: service_b/Dockerfile
    environment:
      TELEMETRY_HOST: "telemetry:50051"
      RABBITMQ_URL: "amqp://guest:guest@rabbitmq:5672/"
      FILE_WORKER_PARTITION_INDEX: "1"
    depends_on:
      rabbitmq:
        condition: service_healthy
      telemetry:
        condition: service_started
    restart: on-failure

  service_b_2:
    build:
      context: .
      dockerfile: service_b/Dockerfile
    environment:
      TELEMETRY_HOST: "telemetry:50051"
      RABBITMQ_URL: "amqp://guest:guest@rabbitmq:5672/"
      FILE_WORKER_PARTITION_INDEX: "2"
    depends_on:
      rabbitmq:
        condition: service_healthy
      telemetry:
        condition: service_started
    restart: on-failure

  service_b_3:
    build:
      context: .
      dockerfile: service_b/Dockerfile
    environment:
      TELEMETRY_HOST: "telemetry:50051"
      RABBITMQ_URL: "amqp://guest:guest@rabbitmq:5672/"
      FILE_WORKER_PARTITION_INDEX: "3"
    depends_on:
      rabbitmq:
        condition: service_healthy
      telemetry:
        condition: service_started
    restart: on-failure
